export const PRIMARY_CONSULTATION_ID = 'blok-m-lez';

export const consultations = [
  {
    id: PRIMARY_CONSULTATION_ID,
    title: 'Rancangan Kawasan Rendah Emisi Terpadu Blok M dan Tarif Parkir Berbasis Emisi',
    shortTitle: 'Kawasan Rendah Emisi Terpadu Blok M',
    status: 'open',
    statusLabel: 'Konsultasi dibuka',
    institution: 'Pemprov DKI Jakarta — simulasi',
    region: 'Jakarta Selatan',
    topic: 'Transportasi & Lingkungan',
    publishedAt: '2026-07-08',
    opensAt: '2026-07-08',
    closesAt: '2026-08-05',
    updatedAt: '2026-07-10',
    stage: 2,
    questionCount: 6,
    responseCount: 1286,
    documentCount: 4,
    affectedGroups: ['Pekerja shift', 'Pelaku UMKM', 'Penyandang disabilitas', 'Komuter', 'Warga Blok M'],
    excerpt: 'Simulasi konsultasi mengenai batas kawasan, tarif parkir disinsentif, pengecualian, masa transisi, dan kesiapan transportasi publik di Blok M.',
    featured: true,
  },
  {
    id: 'trotoar-kebayoran',
    title: 'Rencana Penataan Trotoar dan Titik Naik-Turun Kebayoran Baru',
    shortTitle: 'Penataan Trotoar Kebayoran Baru',
    status: 'analysis',
    statusLabel: 'Masukan sedang dianalisis',
    institution: 'Dinas Bina Marga DKI Jakarta — simulasi',
    region: 'Jakarta Selatan',
    topic: 'Ruang Publik',
    publishedAt: '2026-05-12',
    opensAt: '2026-05-15',
    closesAt: '2026-06-20',
    updatedAt: '2026-07-07',
    stage: 3,
    questionCount: 8,
    responseCount: 842,
    documentCount: 5,
    affectedGroups: ['Pejalan kaki', 'Pedagang', 'Pengguna kursi roda'],
    excerpt: 'Penataan jalur pejalan kaki, akses universal, ruang bongkar muat, dan titik antar-jemput di koridor komersial.',
  },
  {
    id: 'sampah-pasar',
    title: 'Uji Coba Pengangkutan Sampah Pasar Berbasis Waktu dan Pemilahan',
    shortTitle: 'Pengangkutan Sampah Pasar',
    status: 'closed',
    statusLabel: 'Ditutup — menunggu respons',
    institution: 'Dinas Lingkungan Hidup — simulasi',
    region: 'Jakarta',
    topic: 'Lingkungan',
    publishedAt: '2026-04-04',
    opensAt: '2026-04-10',
    closesAt: '2026-05-18',
    updatedAt: '2026-05-20',
    stage: 3,
    questionCount: 7,
    responseCount: 615,
    documentCount: 3,
    affectedGroups: ['Pedagang pasar', 'Petugas kebersihan', 'Warga sekitar'],
    excerpt: 'Pengaturan waktu angkut, kewajiban pemilahan, dan dukungan fasilitas bagi pedagang pasar.',
  },
  {
    id: 'zona-sekolah',
    title: 'Evaluasi Zona Selamat Sekolah dan Pembatasan Kecepatan',
    shortTitle: 'Evaluasi Zona Selamat Sekolah',
    status: 'outcome',
    statusLabel: 'Hasil diterbitkan',
    institution: 'Dinas Perhubungan DKI Jakarta — simulasi',
    region: 'Jakarta',
    topic: 'Keselamatan',
    publishedAt: '2026-01-10',
    opensAt: '2026-01-15',
    closesAt: '2026-02-25',
    updatedAt: '2026-06-28',
    stage: 5,
    questionCount: 9,
    responseCount: 1734,
    documentCount: 6,
    affectedGroups: ['Pelajar', 'Orang tua', 'Pengemudi', 'Sekolah'],
    excerpt: 'Hasil konsultasi mengenai batas kecepatan, desain penyeberangan, dan pengawasan di sekitar sekolah.',
  },
];

export const consultation = {
  ...consultations[0],
  simulationNotice: 'Prototipe layanan — bukan kanal resmi pemerintah. Seluruh rancangan, respons, dan statistik konsultasi merupakan data simulasi.',
  proposition: 'Menerapkan kawasan rendah emisi terpadu di Blok M secara bertahap, disertai tarif parkir berbasis hasil uji emisi dan perlindungan bagi kelompok yang belum memiliki alternatif mobilitas memadai.',
  reason: 'Blok M memiliki konektivitas transportasi publik dan aktivitas ekonomi yang kuat sehingga relevan sebagai lokasi simulasi untuk menguji kebijakan mobilitas rendah emisi yang tetap inklusif.',
  openToChange: [
    'Batas dan jam berlaku kawasan',
    'Besaran serta tahapan tarif parkir disinsentif',
    'Pengecualian dan dukungan bagi kelompok tertentu',
    'Indikator evaluasi enam bulanan',
  ],
  outsideScope: [
    'Penghapusan tujuan pengendalian emisi Jakarta',
    'Perubahan tarif angkutan umum di luar kewenangan rancangan ini',
    'Penindakan kendaraan di luar batas kawasan simulasi',
  ],
  options: [
    { title: 'Tahap bertahap', description: 'Mulai pada jam sibuk, evaluasi enam bulan, lalu perluas berdasarkan data.' },
    { title: 'Tahap penuh', description: 'Terapkan batas kawasan dan tarif disinsentif sepanjang hari sejak masa transisi berakhir.' },
    { title: 'Berbasis koridor', description: 'Batasi intervensi pada koridor dengan akses angkutan umum terkuat terlebih dahulu.' },
  ],
  evidence: [
    { label: 'Konteks resmi', title: 'Peta jalan Kawasan Rendah Emisi Terpadu Jakarta', source: 'Pemprov DKI Jakarta, 24 Juni 2026', url: 'https://www.jakarta.go.id/index.php/siaran-pers/6814-SP-HMS-06-2026' },
    { label: 'Kebijakan berjalan', title: 'Kebijakan parkir disinsentif Jakarta', source: 'Dinas Perhubungan DKI Jakarta', url: 'https://www.jakarta.go.id/page/kebijakan-parkir-disinsentif-jakarta' },
    { label: 'Layanan publik', title: 'Prinsip kebijakan parkir berdasarkan lokasi dan waktu', source: 'Dinas Perhubungan DKI Jakarta', url: 'https://dishub.jakarta.go.id/layanan-parkir/' },
  ],
  documents: [
    { id: 'draft', type: 'Teks rancangan', title: 'Rancangan kebijakan versi 1 — simulasi', format: 'HTML', accessible: true },
    { id: 'academic', type: 'Kajian', title: 'Ringkasan kajian dampak mobilitas dan emisi', format: 'PDF simulasi', accessible: true },
    { id: 'map', type: 'Peta', title: 'Skenario batas kawasan dan simpul transportasi', format: 'Peta interaktif', accessible: true },
    { id: 'easy', type: 'Format alternatif', title: 'Ringkasan mudah dibaca', format: 'HTML + audio', accessible: true },
  ],
  sections: [
    {
      id: 'pasal-3', number: 'Pasal 3', title: 'Tujuan',
      official: 'Kawasan Rendah Emisi Terpadu bertujuan mengurangi paparan emisi transportasi, meningkatkan penggunaan angkutan umum, serta menjaga akses yang adil bagi masyarakat terdampak.',
      plain: 'Kebijakan ingin mengurangi polusi dan kendaraan pribadi tanpa menutup akses bagi orang yang benar-benar membutuhkan perjalanan ke kawasan.',
      affects: 'Seluruh pengguna kawasan Blok M',
      change: 'Menambahkan kewajiban mengukur akses yang adil, bukan hanya penurunan emisi.',
      questionId: 'q2',
    },
    {
      id: 'pasal-7', number: 'Pasal 7', title: 'Waktu dan batas kawasan',
      official: 'Pembatasan kendaraan diberlakukan pada hari kerja pukul 06.00–21.00 dalam batas kawasan yang ditetapkan pada peta lampiran.',
      plain: 'Pada rancangan awal, pembatasan berlaku hampir sepanjang hari kerja. Batas dan jamnya masih dapat berubah melalui konsultasi.',
      affects: 'Komuter, pekerja malam, warga, pengemudi logistik',
      change: 'Usulan konsultasi meminta evaluasi jam malam dan akses bongkar muat.',
      questionId: 'q3',
    },
    {
      id: 'pasal-9', number: 'Pasal 9', title: 'Tarif parkir berbasis emisi',
      official: 'Kendaraan yang belum memenuhi ketentuan uji emisi dikenai tarif parkir disinsentif paling tinggi Rp15.000 per jam tanpa batas harian selama masa uji coba.',
      plain: 'Kendaraan yang belum lulus uji emisi membayar parkir lebih mahal. Besaran, batas harian, dan masa transisi masih dibahas.',
      affects: 'Pengguna kendaraan pribadi dan pekerja dengan jam tidak tetap',
      change: 'Bagian ini menerima usulan batas tarif harian dan masa transisi.',
      questionId: 'q4',
    },
    {
      id: 'pasal-12', number: 'Pasal 12', title: 'Pengecualian dan dukungan',
      official: 'Pengecualian diberikan kepada kendaraan darurat, layanan angkutan umum, dan kendaraan pemegang izin akses khusus.',
      plain: 'Rancangan awal belum menjelaskan secara rinci akses penyandang disabilitas, pekerja shift, atau pelaku usaha kecil.',
      affects: 'Penyandang disabilitas, pekerja shift, UMKM, layanan darurat',
      change: 'Kriteria izin akses khusus menjadi pertanyaan utama konsultasi.',
      questionId: 'q5',
    },
    {
      id: 'pasal-14', number: 'Pasal 14', title: 'Evaluasi',
      official: 'Pelaksanaan dievaluasi setelah dua belas bulan berdasarkan indikator kualitas udara dan volume kendaraan.',
      plain: 'Evaluasi awal hanya melihat emisi dan lalu lintas setelah satu tahun; warga meminta evaluasi lebih cepat dan indikator keterjangkauan.',
      affects: 'Seluruh kelompok terdampak',
      change: 'Usulan versi 2 menambah evaluasi enam bulanan dan indikator sosial.',
      questionId: 'q6',
    },
  ],
  questions: [
    { id: 'q1', section: 'Tentang Anda', type: 'single', prompt: 'Dalam konteks apa Anda paling sering beraktivitas di Blok M?', required: true, options: ['Bekerja atau bersekolah', 'Menjalankan usaha', 'Bertempat tinggal', 'Mengakses layanan atau berbelanja', 'Transit atau berganti moda', 'Lainnya'] },
    { id: 'q2', section: 'Arah kebijakan', type: 'scale', prompt: 'Sejauh mana Anda setuju dengan penerapan kawasan rendah emisi secara bertahap di Blok M?', required: true, options: ['Sangat setuju', 'Setuju', 'Netral', 'Tidak setuju', 'Sangat tidak setuju', 'Belum yakin'] },
    { id: 'q3', section: 'Dampak', type: 'multi', prompt: 'Kelompok mana yang perlu mendapat perhatian khusus?', required: true, options: ['Pekerja shift', 'Penyandang disabilitas', 'Pelaku UMKM', 'Pengemudi logistik', 'Warga kawasan', 'Pengguna angkutan umum'] },
    { id: 'q4', section: 'Risiko', type: 'long', prompt: 'Apa risiko utama dari usulan tarif parkir dan pembatasan kawasan ini?', required: true, hint: 'Ceritakan dampak yang mungkin terjadi dan siapa yang mengalaminya.' },
    { id: 'q5', section: 'Usulan perubahan', type: 'long', prompt: 'Perubahan apa yang Anda usulkan untuk Pasal 9 atau Pasal 12?', required: true, hint: 'Contoh: batas tarif harian, masa transisi, atau kriteria izin akses.' },
    { id: 'q6', section: 'Bukti dan evaluasi', type: 'evidence', prompt: 'Apakah Anda memiliki pengalaman, data, atau sumber pendukung?', required: false, hint: 'Tambahkan URL atau uraian singkat. Unggah berkas hanya disimulasikan.' },
  ],
  publicSubmissions: [
    { id: 's1', name: 'Rina P.', role: 'Pekerja shift', reference: 'Pasal 9', position: 'Menolak sebagian', issue: 'Keterjangkauan', text: 'Tarif progresif dapat membebani pekerja malam yang belum memiliki alternatif transportasi umum setelah jam operasional tertentu.', proposal: 'Tambahkan batas tarif harian dan pengecualian terverifikasi untuk pekerja shift.', relevant: 48, evidence: true, response: 'Direspons' },
    { id: 's2', name: 'Bagus W.', role: 'Pelaku UMKM', reference: 'Pasal 7', position: 'Setuju dengan syarat', issue: 'Logistik usaha', text: 'Jam bongkar muat perlu dipisahkan dari jam tersibuk agar pembatasan tidak memutus pasokan usaha kecil.', proposal: 'Sediakan jendela bongkar muat pukul 04.00–06.00 dan izin satu kali untuk pemasok.', relevant: 36, evidence: true, response: 'Direspons' },
    { id: 's3', name: 'Nadia A.', role: 'Pengguna kursi roda', reference: 'Pasal 12', position: 'Menolak sebagian', issue: 'Akses disabilitas', text: 'Istilah izin akses khusus belum menjamin kendaraan pengantar penyandang disabilitas dapat masuk tanpa proses rumit.', proposal: 'Gunakan verifikasi sederhana dan izinkan kendaraan pendamping yang didaftarkan.', relevant: 71, evidence: false, response: 'Direspons' },
    { id: 's4', name: 'Anonim', role: 'Warga kawasan', reference: 'Pasal 14', position: 'Setuju', issue: 'Evaluasi', text: 'Warga perlu melihat data kualitas udara dan pergeseran lalu lintas ke jalan lingkungan secara berkala.', proposal: 'Publikasikan dashboard evaluasi setiap tiga bulan.', relevant: 29, evidence: true, response: 'Sedang dianalisis' },
    { id: 's5', name: 'Dimas R.', role: 'Komuter', reference: 'Pertanyaan 2', position: 'Sangat setuju', issue: 'Transportasi publik', text: 'Blok M sudah memiliki banyak pilihan transit, tetapi koneksi pejalan kaki antartitik belum selalu nyaman saat hujan.', proposal: 'Prioritaskan kanopi dan penyeberangan sebelum pembatasan penuh.', relevant: 44, evidence: false, response: 'Sedang dianalisis' },
    { id: 's6', name: 'Sari M.', role: 'Pengemudi logistik', reference: 'Pasal 7', position: 'Tidak setuju', issue: 'Logistik usaha', text: 'Pembatasan sepanjang hari kerja terlalu luas untuk pengiriman yang tidak bisa dilakukan sebelum toko buka.', proposal: 'Uji koridor terbatas lebih dulu dan gunakan reservasi waktu bongkar muat.', relevant: 24, evidence: false, response: 'Direspons' },
    { id: 's7', name: 'Fajar H.', role: 'Pengguna MRT', reference: 'Pasal 3', position: 'Setuju', issue: 'Kualitas udara', text: 'Tujuan kebijakan perlu diukur dengan data paparan pejalan kaki, bukan hanya rata-rata kawasan.', proposal: 'Tambahkan sensor di jalur pedestrian utama.', relevant: 39, evidence: true, response: 'Sedang dianalisis' },
    { id: 's8', name: 'Komunitas Akses Kota', role: 'Organisasi masyarakat', reference: 'Pasal 12', position: 'Setuju dengan syarat', issue: 'Akses disabilitas', text: 'Pengecualian harus mencakup kebutuhan mobilitas yang tidak selalu menggunakan kendaraan milik pribadi.', proposal: 'Izin melekat pada pengguna, bukan nomor kendaraan tunggal.', relevant: 83, evidence: true, response: 'Direspons' },
    { id: 's9', name: 'Anonim', role: 'Pelajar', reference: 'Pertanyaan 4', position: 'Setuju', issue: 'Keamanan berjalan', text: 'Peralihan ke transportasi umum harus disertai jalur berjalan yang terang pada malam hari.', proposal: 'Masukkan pencahayaan dan keamanan sebagai indikator kesiapan.', relevant: 31, evidence: false, response: 'Belum direspons' },
    { id: 's10', name: 'Yusuf T.', role: 'Pemilik kendaraan', reference: 'Pasal 9', position: 'Tidak setuju', issue: 'Keterjangkauan', text: 'Kenaikan tarif tidak adil bila lokasi uji emisi dan informasi masa berlaku belum mudah ditemukan.', proposal: 'Berikan masa transisi dan layanan uji emisi bergerak.', relevant: 27, evidence: true, response: 'Direspons' },
  ],
  discussionPosts: [
    { room: 'Keterjangkauan tarif', author: 'Rina P.', role: 'Pekerja shift', reference: 'Pasal 9', text: 'Batas harian lebih mudah dipahami dan diprediksi daripada tarif tanpa batas.', replies: 12, relevant: 34 },
    { room: 'Keterjangkauan tarif', author: 'Yusuf T.', role: 'Pemilik kendaraan', reference: 'Pasal 9', text: 'Apakah diskon masa transisi bisa dikaitkan dengan jadwal uji emisi?', replies: 7, relevant: 19 },
    { room: 'Kesiapan transportasi', author: 'Dimas R.', role: 'Komuter', reference: 'Pertanyaan 4', text: 'Koneksi MRT–terminal bagus, tetapi jalur pejalan kaki perlu perlindungan cuaca.', replies: 9, relevant: 28 },
    { room: 'Kesiapan transportasi', author: 'Maya L.', role: 'Warga', reference: 'Pasal 7', text: 'Perlu data jam operasional untuk pekerja yang pulang setelah tengah malam.', replies: 15, relevant: 42 },
    { room: 'Pekerja & UMKM', author: 'Bagus W.', role: 'Pelaku UMKM', reference: 'Pasal 7', text: 'Reservasi slot bongkar muat mungkin lebih adil daripada pengecualian permanen.', replies: 6, relevant: 26 },
    { room: 'Pekerja & UMKM', author: 'Sari M.', role: 'Pengemudi logistik', reference: 'Pasal 7', text: 'Slot harus cukup fleksibel untuk barang segar dan keterlambatan lalu lintas.', replies: 4, relevant: 17 },
    { room: 'Akses disabilitas', author: 'Nadia A.', role: 'Pengguna kursi roda', reference: 'Pasal 12', text: 'Izin yang melekat pada orang lebih masuk akal karena kendaraan pendamping dapat berganti.', replies: 11, relevant: 55 },
    { room: 'Akses disabilitas', author: 'Komunitas Akses Kota', role: 'Organisasi', reference: 'Pasal 12', text: 'Tolong bedakan akses masuk kawasan dan ketersediaan parkir aksesibel.', replies: 8, relevant: 47 },
    { room: 'Dampak lingkungan', author: 'Fajar H.', role: 'Pengguna MRT', reference: 'Pasal 14', text: 'Data rata-rata bisa menutupi perpindahan polusi ke jalan sekitar.', replies: 5, relevant: 33 },
    { room: 'Dampak lingkungan', author: 'Dr. Lestari', role: 'Peneliti', reference: 'Pasal 14', text: 'Gunakan titik pembanding di luar batas kawasan untuk membaca perubahan dengan lebih baik.', replies: 3, relevant: 38 },
    { room: 'Pertanyaan untuk instansi', author: 'Anonim', role: 'Warga kawasan', reference: 'Pertanyaan 6', text: 'Siapa yang memutuskan perluasan setelah masa uji coba dan di mana hasil evaluasinya diterbitkan?', replies: 2, relevant: 41 },
    { room: 'Pertanyaan untuk instansi', author: 'Ayu K.', role: 'Pelajar', reference: 'Pasal 3', text: 'Apakah keamanan pejalan kaki malam hari masuk ukuran keberhasilan?', replies: 4, relevant: 29 },
  ],
  institutionalResponses: [
    { issue: 'Keterjangkauan bagi pekerja shift', count: 418, groups: ['Pekerja shift', 'Pelaku usaha'], evidence: 'Data jam perjalanan dan 27 uraian pengalaman', consideration: 'Tarif tanpa batas harian berisiko memberi beban tidak proporsional ketika angkutan umum belum tersedia sepanjang waktu.', decision: 'Diterima', tone: 'accepted', outcome: 'Batas tarif harian dan izin pekerja shift ditambahkan.', section: 'Pasal 9 dan Pasal 12' },
    { issue: 'Pengecualian disabilitas tidak jelas', count: 96, groups: ['Penyandang disabilitas', 'Pendamping'], evidence: 'Masukan organisasi dan audit perjalanan simulasi', consideration: 'Izin yang hanya melekat pada kendaraan tidak mencerminkan variasi kebutuhan pendampingan.', decision: 'Diterima', tone: 'accepted', outcome: 'Izin akses melekat pada pengguna yang terverifikasi.', section: 'Pasal 12' },
    { issue: 'Masa transisi terlalu singkat', count: 173, groups: ['Pemilik kendaraan', 'UMKM'], evidence: 'Ketersediaan lokasi uji emisi dan masukan pelaku usaha', consideration: 'Sosialisasi dan akses uji emisi perlu tersedia sebelum tarif penuh.', decision: 'Diterima sebagian', tone: 'partial', outcome: 'Masa transisi diperpanjang dan uji emisi bergerak dijadwalkan.', section: 'Pasal 9' },
    { issue: 'Hapus seluruh kebijakan kawasan rendah emisi', count: 52, groups: ['Pemilik kendaraan'], evidence: 'Pernyataan umum tanpa alternatif pengendalian emisi', consideration: 'Tujuan pengendalian emisi berada di luar ruang perubahan konsultasi, tetapi desain pelaksanaannya tetap dapat diubah.', decision: 'Ditolak dengan alasan', tone: 'rejected', outcome: 'Tujuan dipertahankan; perlindungan dan tahapan implementasi diperkuat.', section: 'Pasal 3' },
    { issue: 'Evaluasi sosial dan perpindahan lalu lintas', count: 211, groups: ['Warga', 'Peneliti', 'Pelajar'], evidence: 'Usulan sensor pembanding dan indikator keamanan', consideration: 'Indikator kualitas udara saja tidak cukup untuk membaca dampak kawasan.', decision: 'Diterima', tone: 'accepted', outcome: 'Evaluasi enam bulanan menambah indikator sosial, keselamatan, dan jalan sekitar.', section: 'Pasal 14' },
  ],
  revisions: [
    { section: 'Pasal 9', before: 'Tarif parkir disinsentif paling tinggi Rp15.000 per jam tanpa batas harian selama masa uji coba.', after: 'Tarif disinsentif diterapkan bertahap dengan batas maksimum harian Rp45.000 selama masa uji coba.', reason: 'Keterjangkauan muncul dalam 418 respons, terutama dari pekerja shift dan pelaku usaha.', status: 'Diterima' },
    { section: 'Pasal 12', before: 'Izin akses khusus diberikan kepada kendaraan yang memenuhi kriteria verifikasi.', after: 'Izin akses khusus diberikan kepada pengguna yang memenuhi kriteria, termasuk penyandang disabilitas dan pekerja shift, serta dapat digunakan pada kendaraan pendamping terdaftar.', reason: 'Masukan menunjukkan kebutuhan mobilitas tidak selalu melekat pada satu kendaraan.', status: 'Diterima' },
    { section: 'Pasal 14', before: 'Pelaksanaan dievaluasi setelah dua belas bulan berdasarkan kualitas udara dan volume kendaraan.', after: 'Pelaksanaan dievaluasi setiap enam bulan berdasarkan kualitas udara, volume kendaraan, keterjangkauan, keselamatan pejalan kaki, dan dampak pada jalan sekitar.', reason: 'Warga meminta indikator sosial dan deteksi perpindahan lalu lintas.', status: 'Diterima' },
  ],
  deliberationSummary: {
    contributions: 126,
    issues: 5,
    answered: 2,
    pending: 3,
    headline: 'Kekhawatiran terbesar adalah keterjangkauan bagi pekerja shift dan kejelasan akses disabilitas.',
  },
};

export const processSteps = [
  'Rancangan diterbitkan',
  'Konsultasi dibuka',
  'Masukan dianalisis',
  'Respons instansi',
  'Hasil dan revisi',
];

export function getConsultation(id = PRIMARY_CONSULTATION_ID) {
  return id === PRIMARY_CONSULTATION_ID ? consultation : consultations.find((item) => item.id === id) || null;
}
