import * as THREE from 'three';
import { createIcons, Landmark, House, Orbit, LayoutDashboard, Activity, Globe2, Plus, Files, TrendingUp, Radio, BadgeCheck, Search, Leaf, BusFront, GraduationCap, HeartPulse, Cpu, Pencil, Trash2, Inbox, X, Save, CheckCircle2 } from 'lucide';
import { listPetitions, createPetition, updatePetition, deletePetition, subscribePetitions } from './petitionStore.js';
import './portal.css';

const iconSet={Landmark,House,Orbit,LayoutDashboard,Activity,Globe2,Plus,Files,TrendingUp,Radio,BadgeCheck,Search,Leaf,BusFront,GraduationCap,HeartPulse,Cpu,Pencil,Trash2,Inbox,X,Save,CheckCircle2};
let petitions=listPetitions(),pendingDelete=null;

const rows=document.querySelector('#petitionRows'),empty=document.querySelector('#emptyState'),editor=document.querySelector('#petitionEditor'),form=document.querySelector('#petitionForm'),deleteDialog=document.querySelector('#deleteDialog');
const categoryIcon={Lingkungan:'leaf',Transportasi:'bus-front',Pendidikan:'graduation-cap',Kesehatan:'heart-pulse',Teknologi:'cpu'};
const shortDate=date=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'}).format(new Date(date));
function filtered(){const q=document.querySelector('#petitionSearch').value.trim().toLowerCase(),status=document.querySelector('#statusFilter').value;return petitions.filter(p=>(status==='Semua'||p.status===status)&&(!q||(p.title+' '+p.category+' '+p.owner).toLowerCase().includes(q)))}
function render(){const data=filtered();rows.innerHTML=data.map((p,i)=>`<tr style="animation-delay:${i*.045}s"><td><div class="petition-title-cell"><span class="category-icon"><i data-lucide="${categoryIcon[p.category]||'files'}"></i></span><div><b>${escapeHtml(p.title)}</b><small>${escapeHtml(p.category)} · ${escapeHtml(p.owner)}</small></div></div></td><td><span class="status-chip ${p.status==='Aktif'?'active':p.status==='Selesai'?'done':''}">${p.status}</span></td><td><b>${Number(p.signatures).toLocaleString('id-ID')}</b><div class="table-progress"><i style="width:${Math.min(100,p.signatures/p.target*100)}%"></i></div></td><td>${Number(p.target).toLocaleString('id-ID')}</td><td>${shortDate(p.updated)}</td><td><div class="row-actions"><button data-action="edit" data-id="${p.id}" aria-label="Edit ${escapeHtml(p.title)}"><i data-lucide="pencil"></i></button><button class="danger" data-action="delete" data-id="${p.id}" aria-label="Hapus ${escapeHtml(p.title)}"><i data-lucide="trash-2"></i></button></div></td></tr>`).join('');empty.classList.toggle('show',!data.length);createIcons({icons:iconSet});updateStats()}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function updateStats(){const total=petitions.length,signs=petitions.reduce((n,p)=>n+Number(p.signatures||0),0),active=petitions.filter(p=>p.status==='Aktif').length,response=petitions.filter(p=>p.signatures>=10000).length;animateNumber('statTotal',total);animateNumber('statSigns',signs);animateNumber('statActive',active);animateNumber('statResponse',response)}
function animateNumber(id,target){const el=document.getElementById(id),start=Number(el.dataset.value||0),begin=performance.now();el.dataset.value=target;const tick=now=>{const p=Math.min(1,(now-begin)/550),value=Math.round(start+(target-start)*(1-Math.pow(1-p,3)));el.textContent=id==='statSigns'&&value>999999?(value/1000000).toFixed(1)+' jt':value.toLocaleString('id-ID');if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
render();subscribePetitions(records=>{petitions=records;render()});

document.querySelector('#petitionSearch').addEventListener('input',render);document.querySelector('#statusFilter').addEventListener('change',render);
document.querySelector('#newPetition').addEventListener('click',()=>openEditor());document.querySelectorAll('[data-close-editor]').forEach(btn=>btn.addEventListener('click',()=>editor.close()));
rows.addEventListener('click',e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const petition=petitions.find(p=>p.id===btn.dataset.id);if(btn.dataset.action==='edit')openEditor(petition);else{pendingDelete=petition.id;deleteDialog.showModal()}});
function openEditor(petition=null){form.reset();document.querySelector('#editorTitle').textContent=petition?'Edit petisi':'Buat petisi baru';document.querySelector('#petitionId').value=petition?.id||'';document.querySelector('#petitionTitle').value=petition?.title||'';document.querySelector('#petitionCategory').value=petition?.category||'Lingkungan';document.querySelector('#petitionStatus').value=petition?.status||'Draft';document.querySelector('#petitionTarget').value=petition?.target||10000;document.querySelector('#petitionSignatures').value=petition?.signatures||0;document.querySelector('#petitionOwner').value=petition?.owner||'';document.querySelector('#petitionDescription').value=petition?.description||'';editor.showModal();requestAnimationFrame(()=>document.querySelector('#petitionTitle').focus())}
form.addEventListener('submit',e=>{e.preventDefault();const id=document.querySelector('#petitionId').value,record={id:id||('petition-'+Date.now()),title:document.querySelector('#petitionTitle').value.trim(),category:document.querySelector('#petitionCategory').value,status:document.querySelector('#petitionStatus').value,target:Number(document.querySelector('#petitionTarget').value),signatures:Number(document.querySelector('#petitionSignatures').value),owner:document.querySelector('#petitionOwner').value.trim(),description:document.querySelector('#petitionDescription').value.trim(),updated:new Date().toISOString().slice(0,10)};if(id)updatePetition(id,record);else createPetition(record);editor.close();showToast(id?'Petisi diperbarui':'Petisi berhasil dibuat',id?'Perubahan terbaru sudah disimpan.':'Gerakan baru masuk ke database lokal.')});
document.querySelector('#cancelDelete').addEventListener('click',()=>deleteDialog.close());document.querySelector('#confirmDelete').addEventListener('click',()=>{deletePetition(pendingDelete);deleteDialog.close();showToast('Petisi dihapus','Data telah dihapus dari perangkat ini.');pendingDelete=null});
function showToast(title,subtitle){const toast=document.querySelector('#portalToast');toast.querySelector('b').textContent=title;toast.querySelector('span').textContent=subtitle;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3200)}
if(new URLSearchParams(location.search).get('action')==='create')openEditor();

// Animated 3D public-signal sculpture in the dashboard hero.
const host=document.querySelector('#dashOrb'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,host.clientWidth/host.clientHeight,.1,50);camera.position.set(0,0,7);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x050a17,2.7));const light=new THREE.PointLight(0xe31f36,22,12);light.position.set(3,3,4);scene.add(light);const sculpture=new THREE.Group();scene.add(sculpture);
const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,4),new THREE.MeshPhysicalMaterial({color:0xb4192d,metalness:.35,roughness:.18,transmission:.3,transparent:true,opacity:.72,wireframe:false}));sculpture.add(orb);const orbWire=new THREE.Mesh(new THREE.IcosahedronGeometry(1.48,2),new THREE.MeshBasicMaterial({color:0xe31f36,wireframe:true,transparent:true,opacity:.16}));sculpture.add(orbWire);
for(let i=0;i<5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(2+i*.25,.012,8,110),new THREE.MeshBasicMaterial({color:i===2?0xe31f36:0xffffff,transparent:true,opacity:i===2?.55:.2}));ring.rotation.set(i*.32,Math.PI/2+i*.27,i*.2);sculpture.add(ring)}
const satellites=[];for(let i=0;i<13;i++){const node=new THREE.Mesh(new THREE.SphereGeometry(i%4===0?.08:.04,12,12),new THREE.MeshBasicMaterial({color:i%4===0?0xe31f36:0xffe8eb}));sculpture.add(node);satellites.push(node)}let lastFrame=0,orbVisible=true;new IntersectionObserver(([entry])=>{orbVisible=entry.isIntersecting},{rootMargin:'100px'}).observe(host);function animate(stamp=0){requestAnimationFrame(animate);if(document.hidden||!orbVisible||stamp-lastFrame<42)return;lastFrame=stamp;const t=stamp*.001;sculpture.rotation.y=t*.12;sculpture.rotation.x=Math.sin(t*.35)*.18;satellites.forEach((node,i)=>{const a=t*(.22+i*.004)+i/satellites.length*Math.PI*2,r=2.05+(i%3)*.35;node.position.set(Math.cos(a)*r,Math.sin(a*1.3+i)*1.3,Math.sin(a)*r)});orb.scale.setScalar(1+Math.sin(t*1.6)*.025);renderer.render(scene,camera)}animate();function resize(){const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}window.addEventListener('resize',resize);
