import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { createIcons, Landmark, Search, ArrowRight, ArrowLeft, ArrowDown, ArrowUpRight, CircleUserRound, Plus, Menu, Radio, Fingerprint, X, Check, CheckCircle2 } from 'lucide';
import { createPetition } from './petitionStore.js';
import './style.css';

const iconSet={Landmark,Search,ArrowRight,ArrowLeft,ArrowDown,ArrowUpRight,CircleUserRound,Plus,Menu,Radio,Fingerprint,X,Check,CheckCircle2};createIcons({icons:iconSet});

const petitions=[
 {category:'Lingkungan',title:'Selamatkan 12.000 hektare hutan adat Papua',excerpt:'Desak penghentian izin pembukaan lahan dan akui hak kelola masyarakat adat.',signatures:84291,target:100000,growth:'+12.481 minggu ini',tone:0xe31f36,tag:'mendesak'},
 {category:'Transportasi',title:'Transportasi publik aman untuk perempuan, 24 jam',excerpt:'Hadirkan petugas, pencahayaan, dan kanal pelaporan terpadu di seluruh moda publik.',signatures:67104,target:100000,growth:'+9.028 minggu ini',tone:0xe31f36,tag:'baru'},
 {category:'Pendidikan',title:'Internet layak untuk setiap sekolah di wilayah 3T',excerpt:'Pastikan koneksi stabil menjadi infrastruktur dasar pendidikan di daerah tertinggal.',signatures:45830,target:100000,growth:'+7.214 minggu ini',tone:0xfffafa,tag:'baru'},
 {category:'Kesehatan',title:'Perluas layanan kesehatan mental di Puskesmas',excerpt:'Sediakan psikolog klinis dan layanan konseling terjangkau di tingkat kecamatan.',signatures:28192,target:100000,growth:'+3.844 minggu ini',tone:0x8f1729,tag:'mendesak'}
];

const list=document.querySelector('#petitionList'); let activeIndex=0;
function renderList(items=petitions){
 list.innerHTML=items.map((p,i)=>`<article class="petition-item ${p===petitions[activeIndex]?'active':''}" data-index="${petitions.indexOf(p)}"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${p.title}</h3><p><b>${p.signatures.toLocaleString('id-ID')} suara</b><span>${p.growth}</span></p></div><div><span class="petition-arrow"><i data-lucide="arrow-up-right"></i></span><div class="mini-progress"><i style="width:${p.signatures/p.target*100}%"></i></div></div></article>`).join('');
 createIcons({icons:iconSet});
 list.querySelectorAll('.petition-item').forEach(el=>el.addEventListener('click',()=>setActive(+el.dataset.index)));
}
function setActive(i){activeIndex=i;const p=petitions[i];renderList();document.querySelector('#focusNumber').textContent=`${String(i+1).padStart(2,'0')} / 04`;document.querySelector('#focusCategory').textContent=p.category;document.querySelector('#focusTitle').textContent=p.title;document.querySelector('#focusExcerpt').textContent=p.excerpt;document.querySelector('#focusSignatures').textContent=p.signatures.toLocaleString('id-ID');document.querySelector('#focusTarget').textContent=p.target.toLocaleString('id-ID');document.querySelector('#focusBar').style.width=`${p.signatures/p.target*100}%`;setMiniColor(p.tone)}
renderList();

document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;renderList(f==='all'?petitions:petitions.filter(p=>p.tag===f))}));
document.querySelector('#heroSearch').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.toLowerCase();document.querySelector('#petisi').scrollIntoView();renderList(q?petitions.filter(p=>(p.title+p.category+p.excerpt).toLowerCase().includes(q)):petitions)});

const modal=document.querySelector('#petitionModal'),quickForm=document.querySelector('#quickPetitionForm');
function setQuickStep(step,direction='forward'){const current=modal.querySelector('.quick-step.active'),next=modal.querySelector(`[data-step="${step}"]`);if(current===next)return;current?.classList.add(direction==='forward'?'step-exit-left':'step-exit-right');next.classList.add('active',direction==='forward'?'step-enter-right':'step-enter-left');requestAnimationFrame(()=>next.classList.add('step-settled'));setTimeout(()=>{current?.classList.remove('active','step-exit-left','step-exit-right');next.classList.remove('step-enter-right','step-enter-left','step-settled')},360);modal.querySelectorAll('.modal-progress span').forEach((dot,i)=>dot.classList.toggle('active',i<step));modal.querySelector('.modal-progress b').textContent=`${step} / 2`}
function openQuickModal(){quickForm.reset();document.querySelector('#quickTarget').value=10000;modal.querySelectorAll('.quick-step').forEach(step=>step.className='quick-step');modal.querySelector('[data-step="1"]').classList.add('active');modal.querySelectorAll('.modal-progress span').forEach((dot,i)=>dot.classList.toggle('active',i===0));modal.querySelector('.modal-progress b').textContent='1 / 2';modal.classList.remove('closing');modal.showModal();requestAnimationFrame(()=>{modal.classList.add('dialog-enter');document.querySelector('#quickTitle').focus()})}
function closeQuickModal(){modal.classList.add('closing');modal.classList.remove('dialog-enter');setTimeout(()=>{modal.close();modal.classList.remove('closing')},280)}
['#createPetition','#bottomCreate'].forEach(sel=>document.querySelector(sel).addEventListener('click',openQuickModal));document.querySelector('.modal-close').addEventListener('click',closeQuickModal);modal.addEventListener('click',event=>{if(event.target===modal)closeQuickModal()});
document.querySelector('#quickNext').addEventListener('click',()=>{const title=document.querySelector('#quickTitle'),owner=document.querySelector('#quickOwner');if(!title.reportValidity()||!owner.reportValidity())return;setQuickStep(2,'forward');setTimeout(()=>document.querySelector('#quickDescription').focus(),180)});document.querySelector('#quickBack').addEventListener('click',()=>setQuickStep(1,'back'));
quickForm.addEventListener('submit',event=>{event.preventDefault();try{const record=createPetition({title:document.querySelector('#quickTitle').value,owner:document.querySelector('#quickOwner').value,category:document.querySelector('#quickCategory').value,target:Number(document.querySelector('#quickTarget').value),description:document.querySelector('#quickDescription').value,status:'Draft',signatures:0});closeQuickModal();showToast('Draf tersimpan ke Dashboard',`“${record.title}” siap dikelola dan diterbitkan.`)}catch(error){showToast('Petisi belum tersimpan',error.message)}});function showToast(title='Dukunganmu tercatat',sub='Terima kasih sudah ikut bersuara.'){const toast=document.querySelector('#toast');toast.querySelector('strong').textContent=title;toast.querySelector('span').textContent=sub;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500)}
document.querySelector('#supportBtn').addEventListener('click',()=>{petitions[activeIndex].signatures++;setActive(activeIndex);showToast()});
document.querySelector('#loginBtn').addEventListener('click',()=>showToast('Portal masuk segera tersedia','Demo ini berfokus pada pengalaman publik.'));
const menuButton=document.querySelector('.menu-btn');menuButton.addEventListener('click',()=>{const header=document.querySelector('.site-header');const open=header.classList.toggle('menu-open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Tutup menu':'Buka menu')});document.querySelectorAll('.site-header nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.site-header').classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}));

document.addEventListener('pointermove',e=>{const glow=document.querySelector('.cursor-glow');glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'none'}],{duration:700,easing:'cubic-bezier(.2,.7,.2,1)',fill:'both'})}),{threshold:.13});document.querySelectorAll('.section-head,.petition-stage,.how-content,.transparency>*,.final-cta>*').forEach(el=>observer.observe(el));
document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count;let start;const step=t=>{start??=t;const p=Math.min((t-start)/1600,1),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=el.dataset.short?`${(v/1000000).toFixed(1)} jt`:v.toLocaleString('id-ID');if(p<1)requestAnimationFrame(step)};requestAnimationFrame(step)});

// Main Three.js civic network scene
const container=document.querySelector('#three-container');const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x050a17,.055);const camera=new THREE.PerspectiveCamera(42,container.clientWidth/container.clientHeight,.1,100);camera.position.set(0,2.4,15);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.1:1.5));renderer.setSize(container.clientWidth,container.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;container.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x050a17,2.1));const key=new THREE.DirectionalLight(0xffe9ec,4);key.position.set(5,8,5);scene.add(key);const fill=new THREE.PointLight(0xe31f36,35,18);fill.position.set(-2,2,3);scene.add(fill);
const world=new THREE.Group();world.position.set(5.6,-.3,0);scene.add(world);
const platformMat=new THREE.MeshPhysicalMaterial({color:0x101a31,metalness:.45,roughness:.36,transparent:true,opacity:.82});
for(let i=0;i<5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(2.5+i*.75,.012,8,120),new THREE.MeshBasicMaterial({color:i===1?0xe31f36:0xffffff,transparent:true,opacity:i===1?.55:.18}));ring.rotation.x=Math.PI/2;ring.position.y=-2.45+i*.02;world.add(ring)}
const podium=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.65,.45,64,1,true),platformMat);podium.position.y=-2.25;world.add(podium);const cap=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.1,.07,64),new THREE.MeshStandardMaterial({color:0x8f1729,metalness:.4,roughness:.25}));cap.position.y=-2.0;world.add(cap);
// Civic monument made of abstract human figures
const figures=new THREE.Group();world.add(figures);const positions=[[0,0,0],[-1.25,-.25,.15],[1.15,-.15,.4],[-.7,-.5,1.1],[.7,-.5,1.15]];
positions.forEach((p,i)=>{const g=new THREE.Group();const mat=new THREE.MeshPhysicalMaterial({color:i===0?0xe31f36:0xf7f4ef,emissive:i===0?0x620713:0x141b2e,emissiveIntensity:.4,metalness:.15,roughness:.28,transmission:i===0?.1:.28,transparent:true,opacity:i===0?.95:.72});const head=new THREE.Mesh(new THREE.SphereGeometry(.25,24,24),mat);head.position.y=1.7;const body=new THREE.Mesh(new THREE.CapsuleGeometry(.35,.95,8,18),mat);body.position.y=.75;body.scale.set(i===0?1.15:1,1.25,1);g.add(head,body);g.position.set(...p);g.scale.setScalar(i===0?1.22:.9);figures.add(g)});
// Civic architecture: a stylised parliament chamber behind the citizen monument
const architecture=new THREE.Group();architecture.position.set(0,-1.9,-3.25);world.add(architecture);
const stoneMat=new THREE.MeshPhysicalMaterial({color:0x17233d,metalness:.42,roughness:.34,transparent:true,opacity:.86});
const glowMat=new THREE.MeshStandardMaterial({color:0xe31f36,emissive:0x6d0816,emissiveIntensity:1.2,metalness:.15,roughness:.3});
const hall=new THREE.Mesh(new THREE.BoxGeometry(4.8,.72,1.25),stoneMat);hall.position.y=.62;architecture.add(hall);
const roof=new THREE.Mesh(new THREE.CylinderGeometry(2.65,2.65,.12,6),stoneMat);roof.rotation.y=Math.PI/6;roof.position.y=1.04;architecture.add(roof);
const dome=new THREE.Mesh(new THREE.SphereGeometry(1.05,32,16,0,Math.PI*2,0,Math.PI/2),new THREE.MeshPhysicalMaterial({color:0xc91d35,metalness:.5,roughness:.2,transmission:.12,transparent:true,opacity:.78}));dome.position.y=1.04;architecture.add(dome);
const beacon=new THREE.Mesh(new THREE.OctahedronGeometry(.13,0),glowMat);beacon.position.y=2.38;architecture.add(beacon);
const beaconStem=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.72,8),glowMat);beaconStem.position.y=2.03;architecture.add(beaconStem);
for(let i=0;i<9;i++){const column=new THREE.Mesh(new THREE.CylinderGeometry(.075,.085,.88,10),i===4?glowMat:stoneMat);column.position.set(-1.8+i*.45,.61,.7);architecture.add(column)}
for(let i=0;i<4;i++){const stair=new THREE.Mesh(new THREE.BoxGeometry(5.3-i*.22,.09,.3),stoneMat);stair.position.set(0,.21-i*.08,1.05+i*.24);architecture.add(stair)}

// Signature towers turn support volume into a data-city around the platform
const towerGeometry=new THREE.BoxGeometry(.18,1,.18);const towerMaterial=new THREE.MeshPhysicalMaterial({color:0xe31f36,emissive:0x08251d,emissiveIntensity:.6,metalness:.28,roughness:.33,transparent:true,opacity:.66});
const towerCount=54;const towers=new THREE.InstancedMesh(towerGeometry,towerMaterial,towerCount);const towerDummy=new THREE.Object3D();
for(let i=0;i<towerCount;i++){const a=i/towerCount*Math.PI*2,r=3.25+(i%3)*.48,h=.25+((i*17)%13)/13*1.45;towerDummy.position.set(Math.cos(a)*r,-2.02+h/2,Math.sin(a)*r);towerDummy.scale.set(1,h,1);towerDummy.rotation.y=-a;towerDummy.updateMatrix();towers.setMatrixAt(i,towerDummy.matrix)}towers.instanceMatrix.needsUpdate=true;world.add(towers);
// Futuristic civic district — a complete low-poly city surrounding the public monument
const city=new THREE.Group();city.position.y=-1.95;world.add(city);
const cityBase=new THREE.Mesh(new THREE.BoxGeometry(9.6,.28,7.6),new THREE.MeshPhysicalMaterial({color:0x071225,metalness:.55,roughness:.38,transparent:true,opacity:.94}));cityBase.position.y=-.2;city.add(cityBase);
const baseEdge=new THREE.LineSegments(new THREE.EdgesGeometry(cityBase.geometry),new THREE.LineBasicMaterial({color:0xfffafa,transparent:true,opacity:.28}));baseEdge.position.copy(cityBase.position);city.add(baseEdge);
const roadMat=new THREE.MeshStandardMaterial({color:0x111a2f,emissive:0x210611,emissiveIntensity:.8,metalness:.2,roughness:.7});const laneMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.45});
[-2.7,0,2.7].forEach(x=>{const road=new THREE.Mesh(new THREE.BoxGeometry(.62,.025,7.25),roadMat);road.position.set(x,-.03,0);city.add(road);const lane=new THREE.Mesh(new THREE.BoxGeometry(.025,.038,7.1),laneMat);lane.position.set(x,.001,0);city.add(lane)});
[-2.25,.15,2.55].forEach(z=>{const road=new THREE.Mesh(new THREE.BoxGeometry(9.25,.025,.58),roadMat);road.position.set(0,-.025,z);city.add(road);const lane=new THREE.Mesh(new THREE.BoxGeometry(9.05,.038,.025),laneMat);lane.position.set(0,.001,z);city.add(lane)});
const district=new THREE.Group();city.add(district);const buildingPalette=[0x8f1729,0xc71f36,0xf4f1ed,0x263552,0x5b1020];let buildingIndex=0;
for(let gx=-4;gx<=4;gx++){for(let gz=-3;gz<=3;gz++){if(gx===0||gz===0||(Math.abs(gx)<2&&Math.abs(gz)<2))continue;const seed=Math.abs(gx*19+gz*31),h=.6+(seed%11)*.21,w=.45+(seed%3)*.12,d=.46+((seed+2)%3)*.13;const mat=new THREE.MeshPhysicalMaterial({color:buildingPalette[seed%buildingPalette.length],emissive:seed%4===0?0x0c3a31:0x03100d,emissiveIntensity:.55,metalness:.38,roughness:.3,transparent:true,opacity:.9});const building=new THREE.Mesh(seed%5===0?new THREE.CylinderGeometry(w*.6,w*.75,h,8):new THREE.BoxGeometry(w,h,d),mat);building.position.set(gx*1.02,h/2,gz*.92);building.rotation.y=seed%5===0?Math.PI/8:0;district.add(building);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(building.geometry),new THREE.LineBasicMaterial({color:seed%4===0?0xe31f36:0xd6dae2,transparent:true,opacity:.18}));building.add(edges);if(seed%3===0){const crown=new THREE.Mesh(new THREE.BoxGeometry(w*1.08,.055,d*1.08),new THREE.MeshBasicMaterial({color:seed%2?0xe31f36:0xff6672,transparent:true,opacity:.72}));crown.position.y=h/2+.04;building.add(crown)}if(seed%4===0){for(let f=1;f<Math.min(5,Math.floor(h/.36));f++){const belt=new THREE.Mesh(new THREE.BoxGeometry(w*1.015,.018,d*1.015),new THREE.MeshBasicMaterial({color:0xfffafa,transparent:true,opacity:.44}));belt.position.y=-h/2+f*.34;building.add(belt)}}buildingIndex++}}
// Detailed textured city model replaces the procedural massing after it is ready
let cityMixer=null,previousCityTime=0;container.dataset.cityModel='loading';const cityLoader=new GLTFLoader();const dracoLoader=new DRACOLoader();dracoLoader.setDecoderPath('/draco/');dracoLoader.setWorkerLimit(1);cityLoader.setDRACOLoader(dracoLoader);if(!new URLSearchParams(location.search).has('lite'))cityLoader.load('/models/LittlestTokyo.glb',gltf=>{const detailedCity=gltf.scene;detailedCity.rotation.y=-Math.PI*.12;detailedCity.updateMatrixWorld(true);const rawBounds=new THREE.Box3().setFromObject(detailedCity),rawSize=rawBounds.getSize(new THREE.Vector3()),fitScale=8.4/Math.max(rawSize.x,rawSize.z);detailedCity.scale.setScalar(fitScale);detailedCity.updateMatrixWorld(true);const fittedBounds=new THREE.Box3().setFromObject(detailedCity),fittedCenter=fittedBounds.getCenter(new THREE.Vector3());detailedCity.position.set(-fittedCenter.x,-fittedBounds.min.y+.02,-fittedCenter.z);city.add(detailedCity);district.visible=false;container.dataset.cityModel='loaded'},undefined,error=>{container.dataset.cityModel='failed';console.error('Detailed city model failed to load',error)});else container.dataset.cityModel='skipped';
// Elevated transit loop and autonomous vehicles
const transitCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-4.1,.55,-2.9),new THREE.Vector3(0,.8,-3.25),new THREE.Vector3(4.1,.55,-2.9),new THREE.Vector3(4.35,.65,.3),new THREE.Vector3(3.8,.58,3.05),new THREE.Vector3(0,.76,3.25),new THREE.Vector3(-4.1,.55,2.9),new THREE.Vector3(-4.35,.65,.1)],true,'catmullrom',.25);
const transitRail=new THREE.Mesh(new THREE.TubeGeometry(transitCurve,160,.045,8,true),new THREE.MeshStandardMaterial({color:0xe31f36,emissive:0x620713,emissiveIntensity:1.4,metalness:.65,roughness:.18}));city.add(transitRail);
const transitVehicles=[];for(let i=0;i<5;i++){const vehicle=new THREE.Group();const shell=new THREE.Mesh(new THREE.BoxGeometry(.38,.16,.2),new THREE.MeshStandardMaterial({color:i===0?0xe31f36:0xfff4f2,emissive:i===0?0x620713:0x25111a,emissiveIntensity:1,metalness:.3,roughness:.22}));vehicle.add(shell);const light=new THREE.Mesh(new THREE.BoxGeometry(.08,.025,.205),new THREE.MeshBasicMaterial({color:0xffffff}));light.position.x=.14;vehicle.add(light);city.add(vehicle);transitVehicles.push(vehicle)}
// Holographic policy tower, radar discs, and aerial civic beacons
const holoTower=new THREE.Group();holoTower.position.set(3.55,.05,-1.15);city.add(holoTower);const holoBeam=new THREE.Mesh(new THREE.CylinderGeometry(.38,.62,3.7,16,1,true),new THREE.MeshBasicMaterial({color:0xe31f36,transparent:true,opacity:.055,side:THREE.DoubleSide,depthWrite:false}));holoBeam.position.y=1.85;holoTower.add(holoBeam);for(let i=0;i<5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.42+i*.08,.012,6,40),new THREE.MeshBasicMaterial({color:i===2?0xe31f36:0xe31f36,transparent:true,opacity:.55}));ring.rotation.x=Math.PI/2;ring.position.y=.55+i*.62;holoTower.add(ring)}const holoCore=new THREE.Mesh(new THREE.IcosahedronGeometry(.3,1),new THREE.MeshBasicMaterial({color:0xe31f36,wireframe:true,transparent:true,opacity:.8}));holoCore.position.y=3.45;holoTower.add(holoCore);
const drones=[];for(let i=0;i<7;i++){const drone=new THREE.Group();const body=new THREE.Mesh(new THREE.OctahedronGeometry(.1,0),new THREE.MeshStandardMaterial({color:i%3===0?0xe31f36:0xfffafa,emissive:0x620713,emissiveIntensity:1}));drone.add(body);const wings=new THREE.Mesh(new THREE.BoxGeometry(.38,.018,.07),new THREE.MeshBasicMaterial({color:0xd9dde6,transparent:true,opacity:.7}));drone.add(wings);city.add(drone);drones.push(drone)}
// Civic trees soften the district while retaining the miniature low-poly language
const treeMat=new THREE.MeshStandardMaterial({color:0x65c489,roughness:.8});const trunkMat=new THREE.MeshStandardMaterial({color:0x284a3b,roughness:1});for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=2.05+(i%2)*.34;const tree=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.28,6),trunkMat);trunk.position.y=.14;const crown=new THREE.Mesh(new THREE.ConeGeometry(.16,.45,7),treeMat);crown.position.y=.47;tree.add(trunk,crown);tree.position.set(Math.cos(a)*r,0,Math.sin(a)*r);city.add(tree)}

// Floating public records and orbiting policy milestones
const records=new THREE.Group();world.add(records);const recordMat=new THREE.MeshPhysicalMaterial({color:0xfffafa,metalness:.15,roughness:.22,transmission:.35,transparent:true,opacity:.28,side:THREE.DoubleSide});
for(let i=0;i<9;i++){const card=new THREE.Mesh(new THREE.BoxGeometry(.85,.5,.018),recordMat);const a=i/9*Math.PI*2+.3;card.position.set(Math.cos(a)*(4.7+(i%2)*.55),-.2+((i*7)%9)*.48,Math.sin(a)*(4.7+(i%2)*.55));card.lookAt(0,.6,0);const bar=new THREE.Mesh(new THREE.BoxGeometry(.5,.018,.025),new THREE.MeshBasicMaterial({color:i%3===0?0xe31f36:0xff6672,transparent:true,opacity:.55}));bar.position.set(0,.12,.02);card.add(bar);records.add(card)}
const milestones=new THREE.Group();world.add(milestones);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const g=new THREE.Group();g.position.set(Math.cos(a)*5.8,(i%4-1.5)*.7,Math.sin(a)*5.8);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(i%4===0?.13:.07,1),i%4===0?glowMat:new THREE.MeshBasicMaterial({color:0xf7f4ef}));g.add(core);const halo=new THREE.Mesh(new THREE.TorusGeometry(i%4===0?.23:.14,.008,6,28),new THREE.MeshBasicMaterial({color:i%4===0?0xe31f36:0xf7f4ef,transparent:true,opacity:.42}));halo.rotation.x=Math.PI/2;g.add(halo);milestones.add(g)}

// Support streams arc from citizens toward the public chamber
const streams=new THREE.Group();world.add(streams);for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=5.4+(i%3)*.45;const start=new THREE.Vector3(Math.cos(a)*r,-1.4+(i%5)*.5,Math.sin(a)*r);const end=new THREE.Vector3((i%3-1)*.35,1.1+(i%4)*.25,-1.6);const mid=start.clone().lerp(end,.5);mid.y+=2.1+(i%3)*.3;const curve=new THREE.QuadraticBezierCurve3(start,mid,end);const stream=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(32)),new THREE.LineBasicMaterial({color:i%5===0?0xe31f36:0x8f1729,transparent:true,opacity:i%5===0?.26:.1}));streams.add(stream)}
const lineMat=new THREE.LineBasicMaterial({color:0xfffafa,transparent:true,opacity:.22});const nodeMat=new THREE.MeshBasicMaterial({color:0xe31f36});
for(let i=0;i<36;i++){const a=i/36*Math.PI*2;const radius=3.2+Math.random()*3;const y=(Math.random()-.5)*5;const node=new THREE.Mesh(new THREE.SphereGeometry(i%7===0?.07:.025,8,8),nodeMat.clone());node.material.opacity=i%7===0?.8:.35;node.material.transparent=true;node.position.set(Math.cos(a)*radius,y,Math.sin(a)*radius);world.add(node);const points=[node.position.clone(),new THREE.Vector3((Math.random()-.5)*1.8,(Math.random()-.5)*2.8,(Math.random()-.5)*1.8)];world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),lineMat))}
const particlesGeo=new THREE.BufferGeometry(),particleCount=900,arr=new Float32Array(particleCount*3);for(let i=0;i<particleCount;i++){const r=4+Math.random()*8,a=Math.random()*Math.PI*2;arr[i*3]=Math.cos(a)*r;arr[i*3+1]=(Math.random()-.5)*11;arr[i*3+2]=Math.sin(a)*r}particlesGeo.setAttribute('position',new THREE.BufferAttribute(arr,3));const particles=new THREE.Points(particlesGeo,new THREE.PointsMaterial({color:0xfffafa,size:.025,transparent:true,opacity:.38}));world.add(particles);
camera.lookAt(2.65,.15,0);const clock=new THREE.Clock();let mx=0,my=0,lastMainFrame=0;document.addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});function animate(frameStamp=0){requestAnimationFrame(animate);if(frameStamp-lastMainFrame<33)return;lastMainFrame=frameStamp;const t=clock.getElapsedTime();if(cityMixer)cityMixer.update(Math.min(.033,t-previousCityTime));previousCityTime=t;world.rotation.y=t*.025+mx*.1;world.rotation.x=my*.025;figures.position.y=Math.sin(t*.8)*.09;architecture.position.y=-1.9+Math.sin(t*.45)*.035;beacon.rotation.y=t*1.4;records.rotation.y=-t*.035;records.children.forEach((card,i)=>card.position.y+=Math.sin(t*.7+i)*.0007);milestones.rotation.y=t*.09;milestones.children.forEach((node,i)=>{node.children[1].rotation.z=t*(i%2?.65:-.65)});streams.rotation.y=Math.sin(t*.16)*.08;transitVehicles.forEach((vehicle,i)=>{const u=(t*.035+i/transitVehicles.length)%1,pos=transitCurve.getPointAt(u),next=transitCurve.getPointAt((u+.006)%1);vehicle.position.copy(pos);vehicle.lookAt(next)});holoTower.children.slice(1,6).forEach((ring,i)=>ring.rotation.z=t*(i%2?.22:-.22));holoCore.rotation.set(t*.35,t*.55,0);drones.forEach((drone,i)=>{const a=t*(.16+i*.008)+i/7*Math.PI*2,r=3.1+(i%3)*.72;drone.position.set(Math.cos(a)*r,2.15+(i%3)*.52+Math.sin(t+i)*.14,Math.sin(a)*r);drone.rotation.y=-a});particles.rotation.y=-t*.018;renderer.render(scene,camera)}animate();

// Mini orbital data sculpture in active card
const miniCanvas=document.querySelector('#miniCanvas'),mScene=new THREE.Scene(),mCamera=new THREE.PerspectiveCamera(40,1,.1,100);mCamera.position.z=7;const mRenderer=new THREE.WebGLRenderer({canvas:miniCanvas,alpha:true,antialias:true});mRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const orbGroup=new THREE.Group();mScene.add(orbGroup);let orbMat=new THREE.MeshBasicMaterial({color:petitions[0].tone,wireframe:true,transparent:true,opacity:.32});const ico=new THREE.Mesh(new THREE.IcosahedronGeometry(1.65,2),orbMat);orbGroup.add(ico);for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(2+i*.27,.012,8,90),new THREE.MeshBasicMaterial({color:petitions[0].tone,transparent:true,opacity:.35}));r.rotation.set(Math.random()*2,Math.random()*2,Math.random()*2);orbGroup.add(r)}const pLight=new THREE.PointLight(0xe31f36,6);pLight.position.set(2,2,3);mScene.add(pLight);function setMiniColor(color){orbGroup.children.forEach(c=>c.material.color.setHex(color))}function resizeMini(){const box=miniCanvas.parentElement.getBoundingClientRect();mRenderer.setSize(box.width,box.height,false);mCamera.aspect=box.width/box.height;mCamera.updateProjectionMatrix()}let lastMiniFrame=0;function animateMini(frameStamp=0){requestAnimationFrame(animateMini);if(frameStamp-lastMiniFrame<33)return;lastMiniFrame=frameStamp;orbGroup.rotation.x+=.003;orbGroup.rotation.y+=.005;mRenderer.render(mScene,mCamera)}resizeMini();animateMini();
function resize(){const w=container.clientWidth,h=container.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);resizeMini()}window.addEventListener('resize',resize);
